language: rust
env:
    global:
        - secure: rDjjGIgwAUDCFEl4BrcWQ/A/u/nrFSdO2wqiMFsmXNg5NbV8ZnoMFN6gW9+NIDGrV3NZQpkrfTGqEAHj7wHc417v9JDNrUdxMAJb02fDx0Xqg1fkeusBps1+JBvQexMk98ThQkaQPCA0Xs+38Y9l7xWDUqzJfvZxwTXW4NzdTnk=
script:
    - cargo build -v
    - cargo test -v
    - cargo doc --no-deps -v
after_success:
    - cp -R target/doc doc
    - curl http://www.rust-ci.org/artifacts/put?t=$RUSTCI_TOKEN | sh
    - rm -r doc
